# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - xgantry_baselink
    - ytrackplate_xgantry
    - joint_s
    - joint_l
    - joint_e
    - joint_u
    - joint_r
    - joint_b
    - joint_t
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: robot/wavetank_gantry_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - xgantry_baselink
      - ytrackplate_xgantry

  - name: robot/wavetank_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_s
      - joint_l
      - joint_e
      - joint_u
      - joint_r
      - joint_b
      - joint_t


wavetank_gantry_controller:
  type: effort_controllers/JointTrajectoryController
  joints: 
    - xgantry_baselink
    - ytrackplate_xgantry

  gains:
    xgantry_baselink: {p: 30000.0, i: 0, d: 8000.0}
    ytrackplate_xgantry: {p: 50000, i: 0.0, d: 1000}


wavetank_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints: 
    - joint_s
    - joint_l
    - joint_e
    - joint_u
    - joint_r
    - joint_b
    - joint_t

  gains:
    joint_s: { p: 100, d: 20, i: 0} 
    joint_l: { p: 100, d: 30, i: 0}
    joint_e: { p: 100, d: 30, i: 0}
    joint_u: { p: 100, d: 30, i: 0}
    joint_r: { p: 100, d: 30, i: 0}
    joint_b: { p: 100, d: 30, i: 0}
    joint_t: { p: 1, d: 0.1, i: 0}

gantry_controller:
    type: effort_controllers/JointTrajectoryController
    joints: 
      - xgantry_baselink
      - ytrackplate_xgantry 

    gains:
        xgantry_baselink: {p: 30000.0, i: 0, d: 8000.0}
        ytrackplate_xgantry: {p: 50000, i: 0.0, d: 1000}

