<!--robot:-->
  controller_list:
  - name: wavetank_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: 
      - xgantry_baselink
      - ytrackplate_xgantry
      - joint_s
      - joint_l
      - joint_e
      - joint_u
      - joint_r
      - joint_b
      - joint_t
