#this file was created for collecting parameter estimation data for the gantry. The actual robot_control.yaml is renamed to originalrobot_control.yaml

robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  xgantry_baselink_controller:
    type: effort_controllers/JointPositionController
    joint: xgantry_baselink
    pid: {p: 30000.0, i: 0, d: 8000.0}

  ytrackplate_xgantry_controller:
    type: effort_controllers/JointPositionController
    joint: ytrackplate_xgantry
    pid: {p: 50000, i: 0.0, d: 1000}