robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  wavetank_controller:
    type: effort_controllers/JointTrajectoryController
    joints: 
      - xgantry_baselink
      - ytrackplate_xgantry
      - joint_s
      - joint_l
      - joint_e
      - joint_u
      - joint_r
      - joint_b
      - joint_t

    gains:
        xgantry_baselink: { p: 9500.0, i: 0, d: 18000}
        ytrackplate_xgantry: {p: 10000.0, i: 0.0, d: 1000.0}
        joint_s: { p: 100, d: 10, i: 0.01 }
        joint_l: { p: 100, d: 10, i: 0.01 }
        joint_e: { p: 100, d: 10, i: 0.01 }
        joint_u: { p: 100, d: 10, i: 0.01 }
        joint_r: { p: 100, d: 10, i: 0.01 }
        joint_b: { p: 100, d: 10, i: 0.01 }
        joint_t: { p: 100, d: 10, i: 0.01 }

    constraints:
        goal_time: 2.0

    state_publish_rate: 25

