#this file was created for collecting parameter estimation data for the gantry. The actual ros_controllers.yaml is renamed to originalros_controllers.yaml

# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - xgantry_baselink
    - ytrackplate_xgantry

  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: robot/gantry_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - xgantry_baselink
      - ytrackplate_xgantry





gantry_controller:
    type: effort_controllers/JointTrajectoryController
    joints: 
      - xgantry_baselink
      - ytrackplate_xgantry 

    gains:
        xgantry_baselink: {p: 0.0, i: 0.0, d: 0.0}
        ytrackplate_xgantry: {p: 0.0, i: 0.0, d: 0.0}

